- name: install domain keys
  copy: content="{{ item.private_key }}"
        dest={{ letsencrypt_lib_dir }}/private/{{ item.name }}.key
        owner=letsencrypt group=ssl-cert mode=0640
  with_items: "{{ letsencrypt_certificates }}"

- name: Install csr keys
  copy: content="{{ item.csr }}"
        dest={{ letsencrypt_lib_dir }}/private/{{ item.name }}.csr
        owner=letsencrypt group=ssl-cert mode=0640
  with_items: "{{ letsencrypt_certificates }}"

- name: Install certs
  copy: content="{{ item.cert }}"
        dest={{ letsencrypt_lib_dir }}/certs/{{ item.name }}.crt
        owner=letsencrypt group=ssl-cert mode=0640 force=no
  with_items: "{{ letsencrypt_certificates }}"
  when: item.cert != ""

- name: Install pems
  shell: cp {{ letsencrypt_lib_dir }}/certs/{{ item.name }}.crt {{ letsencrypt_lib_dir }}/certs/{{ item.name }}.pem
  args:
     creates: "{{ letsencrypt_lib_dir }}/certs/{{ item.name }}.pem"
  with_items: "{{ letsencrypt_certificates }}"
  when: item.cert != ""

- name: set rights on pems
  file: path={{ letsencrypt_lib_dir }}/certs/{{ item.name }}.pem owner=letsencrypt group=letsencrypt mode=0644
  with_items: "{{ letsencrypt_certificates }}"
  when: item.cert != ""

- name: install domain files
  copy: content=""
        dest={{ letsencrypt_lib_dir }}/domains/{{ item.name }}
        owner=letsencrypt group=letsencrypt mode=0644
  with_items: "{{ letsencrypt_certificates }}"
