- name: create apache snippet directory
  file: path=/etc/apache2/snippets owner=root group=root mode=0755 state=directory
  when: letsencrypt_web_server == "apache"

- name: copy apache snippet
  copy: src=snippet_letsencrypt_apache.conf dest=/etc/apache2/snippets/letsencrypt_challenge.conf mode=0644
  when: letsencrypt_web_server == "apache"

- name: copy apache snippet for redirection
  copy: src=snippet_letsencrypt_apache_redirect.conf dest=/etc/apache2/snippets/letsencrypt_redirect80.conf mode=0644
  when: letsencrypt_web_server == "apache"

- name: create nginx snippet directory
  file: path=/etc/nginx/snippets owner=root group=root mode=0755 state=directory
  when: letsencrypt_web_server == "nginx"

- name: copy nginx snippet
  copy: src=snippet_letsencrypt_nginx.conf dest=/etc/nginx/snippets/letsencrypt_challenge.conf mode=0644
  when: letsencrypt_web_server == "nginx"
